### ISSUE TITLE
[QUESTION] Vercel deployment

### ISSUE THREAD

**Issue by JBYT27** [DillonB07/Spotter#6]
So I saw that you're trying to deploy the django app to Vercel, and I tried the same with Flask, but it failed.

Do you know how to successfully deploy a python app to a vercel app?

**Comment by DillonB07** [comment]
No. I'm not sure it's possible.

**Comment by DillonB07** [comment]
A python app/project using Flask/Django relies on a backend. However, vercel apps only have frontend. If it has logic to it, that happens on the client-side or has a separate backend.

Therefore, if your project CAN be built (like React) then vercel can deploy it. But because Flask/Django rely on Jinja templates and dynamically update them vercel can't deploy it.

**Comment by JBYT27** [comment]
Oh, okay! Thanks for letting me know!
